### ISSUE TITLE
Transformation #1 failed

### ISSUE THREAD

**Issue by KORN0529** [dreamnettech/dreamtime#105]
Transformation #1 failed
Apparently you have run out of RAM on your GPU! Try a photo of smaller size or free all possible GPU use.

For more information please take a screenshot and report the following on Github or here:

        Error: [8472] Failed to execute script main
[11472] Failed to execute script main Traceback (most recent call last): File "C:\BuildAgent\work\19c514061bf819a4\src\cli\main.py", line 346, in <module> File "C:\BuildAgent\work\19c514061bf819a4\src\cli\main.py", line 243, in main File "C:\BuildAgent\work\19c514061bf819a4\src\cli\run.py", line 151, in process File "C:\BuildAgent\work\19c514061bf819a4\src\cli\gan.py", line 100, in inference File "C:\BuildAgent\work\19c514061bf819a4\src\cli\gan.py", line 259, in forward File "C:\Program Files\Python36\lib\site-packages\torch\nn\modules\module.py", line 493, in call File "C:\Program Files\Python36\lib\site-packages\torch\nn\modules\container.py", line 92, in forward File "C:\Program Files\Python36\lib\site-packages\torch\nn\modules\module.py", line 493, in call File "C:\Program Files\Python36\lib\site-packages\torch\nn\modules\conv.py", line 796, in forward RuntimeError: CUDA out of memory. Tried to allocate 144.00 MiB (GPU 0; 3.00 GiB total capacity; 795.79 MiB already allocated; 0 bytes free; 38.21 MiB cached)

Traceback (most recent call last): File "C:\BuildAgent\work\19c514061bf819a4\src\cli\main.py", line 346, in <module> File "C:\BuildAgent\work\19c514061bf819a4\src\cli\main.py", line 243, in main File "C:\BuildAgent\work\19c514061bf819a4\src\cli\run.py", line 151, in process File "C:\BuildAgent\work\19c514061bf819a4\src\cli\gan.py", line 100, in inference File "C:\BuildAgent\work\19c514061bf819a4\src\cli\gan.py", line 259, in forward File "C:\Program Files\Python36\lib\site-packages\torch\nn\modules\module.py", line 493, in call File "C:\Program Files\Python36\lib\site-packages\torch\nn\modules\container.py", line 92, in forward File "C:\Program Files\Python36\lib\site-packages\torch\nn\modules\module.py", line 493, in call File "C:\Program Files\Python36\lib\site-packages\torch\nn\modules\conv.py", line 796, in forward RuntimeError: CUDA out of memory. Tried to allocate 144.00 MiB (GPU 0; 3.00 GiB total capacity; 795.79 MiB already allocated; 0 bytes free; 76.21 MiB cached)

**Comment by KORN0529** [comment]
Second problem 
Transformation #1 failed
DreamPower has reported that the photo has been transformed but the file does not exist! This may be due to a problem saving the photo, verify that DreamPower has write permissions and that your Antivirus is not detecting false positives. It is also possible that DreamPower is ending abruptly due to a major problem.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Enviroment (please complete the following information):**
 - Version 1.1.0
 - OS: [Windows 10 64], 8GB, Nvidia GTX 1060 3GB

**Comment by kolessios** [comment]
The first problem is evident, as the error message says your GPU has run out of memory, try to close all possible programs that may be using your GPU.

The second problem is usually caused by having DreamPower or the Models folder in a place with special characters or insufficient permissions (this problem is usually common in non-English operating systems), try changing the paths of the folders in `Settings -> Folders` or reinstall DreamTime in another location.
