### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by k128** [dreamnettech/dreamtime#112]
I get the following error seemingly at random:
Error: [47556] Failed to execute script main
Traceback (most recent call last): File "C:\BuildAgent\work\19c514061bf819a4\src\cli\main.py", line 346, in <module> File "C:\BuildAgent\work\19c514061bf819a4\src\cli\main.py", line 243, in main File "C:\BuildAgent\work\19c514061bf819a4\src\cli\run.py", line 151, in process File "C:\BuildAgent\work\19c514061bf819a4\src\cli\gan.py", line 100, in inference File "C:\BuildAgent\work\19c514061bf819a4\src\cli\gan.py", line 259, in forward File "C:\Program Files\Python36\lib\site-packages\torch\nn\modules\module.py", line 493, in call File "C:\Program Files\Python36\lib\site-packages\torch\nn\modules\container.py", line 92, in forward File "C:\Program Files\Python36\lib\site-packages\torch\nn\modules\module.py", line 493, in call File "C:\Program Files\Python36\lib\site-packages\torch\nn\modules\conv.py", line 338, in forward RuntimeError: [enforce fail at ..\c10\core\CPUAllocator.cpp:62] data. DefaultCPUAllocator: not enough memory: you tried to allocate %dGB. Buy new RAM!3

I have 16GB of RAM and task manager does not show me being anywhere near 100%.  

Rerunning multiple times eventually works.

 - Version 1.1.0
 - OS: Windows 10

**Comment by kolessios** [comment]
Right now I can't think of any obvious reason why this could happen. Perhaps some program (antivirus) may be limiting the operation of the program? Any additional information about this problem is welcome.
