### ISSUE TITLE
Transformation #1 failed

### ISSUE THREAD

**Issue by Joeelliott8** [dreamnettech/dreamtime#115]
![image](https://user-images.githubusercontent.com/57543994/68508492-d0258780-026e-11ea-9736-56103fa840f4.png)

I have updated Nvidia driver but didn't solve the issue.

Following the details about the issue explained:

Error: [340] Failed to execute script main
Traceback (most recent call last): File "C:\BuildAgent\work\19c514061bf819a4\src\cli\main.py", line 346, in <module> File "C:\BuildAgent\work\19c514061bf819a4\src\cli\main.py", line 243, in main File "C:\BuildAgent\work\19c514061bf819a4\src\cli\run.py", line 146, in process File "C:\BuildAgent\work\19c514061bf819a4\src\cli\gan.py", line 85, in initialize File "C:\BuildAgent\work\19c514061bf819a4\src\cli\gan.py", line 172, in defineG File "C:\Program Files\Python36\lib\site-packages\torch\nn\modules\module.py", line 265, in cuda File "C:\Program Files\Python36\lib\site-packages\torch\nn\modules\module.py", line 193, in apply File "C:\Program Files\Python36\lib\site-packages\torch\nn\modules\module.py", line 193, in apply File "C:\Program Files\Python36\lib\site-packages\torch\nn\modules\module.py", line 199, in apply File "C:\Program Files\Python36\lib\site-packages\torch\nn\modules\module.py", line 265, in <lambda> File "C:\Program Files\Python36\lib\site-packages\torch\cuda__init.py", line 162, in lazyinit File "C:\Program Files\Python36\lib\site-packages\torch\cuda_init__.py", line 91, in check_driver AssertionError: The NVIDIA driver on your system is too old (found version 9010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver.

[10068] Failed to execute script main Traceback (most recent call last): File "C:\BuildAgent\work\19c514061bf819a4\src\cli\main.py", line 346, in <module> File "C:\BuildAgent\work\19c514061bf819a4\src\cli\main.py", line 243, in main File "C:\BuildAgent\work\19c514061bf819a4\src\cli\run.py", line 146, in process File "C:\BuildAgent\work\19c514061bf819a4\src\cli\gan.py", line 85, in initialize File "C:\BuildAgent\work\19c514061bf819a4\src\cli\gan.py", line 172, in defineG File "C:\Program Files\Python36\lib\site-packages\torch\nn\modules\module.py", line 265, in cuda File "C:\Program Files\Python36\lib\site-packages\torch\nn\modules\module.py", line 193, in apply File "C:\Program Files\Python36\lib\site-packages\torch\nn\modules\module.py", line 193, in apply File "C:\Program Files\Python36\lib\site-packages\torch\nn\modules\module.py", line 199, in apply File "C:\Program Files\Python36\lib\site-packages\torch\nn\modules\module.py", line 265, in <lambda> File "C:\Program Files\Python36\lib\site-packages\torch\cuda__init.py", line 162, in lazyinit File "C:\Program Files\Python36\lib\site-packages\torch\cuda_init__.py", line 91, in check_driver AssertionError: The NVIDIA driver on your system is too old (found version 9010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver.

**Comment by kolessios** [comment]
Thank you for your report, however the error message tells you the problem, if the drivers are already updated then your GPU is not compatible with the program, you must use CPU.
