### ISSUE TITLE
Transformation #1 failed

### ISSUE THREAD

**Issue by ReDead12** [dreamnettech/dreamtime#118]
This happens whenever i try to nudify a photo. I have tried reinstalling it and also changing its location. 

Transformation #1 failed
The algorithm had a problem decoding some characters. This is usually caused by being installed in a location with special characters (accents, spaces, etc.). Please reinstall the program in another location.

        Error: [8316] Failed to execute script main
Traceback (most recent call last): File "C:\BuildAgent\work\19c514061bf819a4\src\cli\main.py", line 346, in <module> File "C:\BuildAgent\work\19c514061bf819a4\src\cli\main.py", line 243, in main File "C:\BuildAgent\work\19c514061bf819a4\src\cli\run.py", line 146, in process File "C:\BuildAgent\work\19c514061bf819a4\src\cli\gan.py", line 85, in initialize File "C:\BuildAgent\work\19c514061bf819a4\src\cli\gan.py", line 172, in defineG File "C:\Program Files\Python36\lib\site-packages\torch\nn\modules\module.py", line 265, in cuda File "C:\Program Files\Python36\lib\site-packages\torch\nn\modules\module.py", line 193, in apply File "C:\Program Files\Python36\lib\site-packages\torch\nn\modules\module.py", line 193, in apply File "C:\Program Files\Python36\lib\site-packages\torch\nn\modules\module.py", line 199, in apply File "C:\Program Files\Python36\lib\site-packages\torch\nn\modules\module.py", line 265, in <lambda> File "C:\Program Files\Python36\lib\site-packages\torch\cuda__init.py", line 164, in lazyinit File "C:\Program Files\Python36\lib\site-packages\torch\cuda_init__.py", line 60, in loadcudart File "C:\Program Files\Python36\lib\site-packages\torch\cuda_init__.py", line 33, in findcudawindows_lib UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 13: invalid start byte

 - Version [e.g. 1.1.0]
 - OS: Windows 10 home 64 bits

**Comment by ReDead12** [comment]
Ok, i tried changing the device from the gpu to the cpu and now it seems that could work, but before like a minute i get a new error:
Transformation #1 failed
DreamPower has reported that the photo has been transformed but the file does not exist! This may be due to a problem saving the photo, verify that DreamPower has write permissions and that your Antivirus is not detecting false positives. It is also possible that DreamPower is ending abruptly due to a major problem.
