### ISSUE TITLE
Failed to get the installed DreamPower version

### ISSUE THREAD

**Issue by medianami** [dreamnettech/dreamtime#183]
**Describe the bug**
Upon attempting to update DreamPower to v1.2.11, DreamTime will display a "CHECK ERROR!", with the description: Failed to get the installed DreamPower version. Please fix this problem before continuing.

**To Reproduce**
1. Open DreamTime
2. Click on 'Update' to update DreamPower to v1.2.11
3. Wait for the file to download and install

**Expected behavior**
On previous versions, this would always work and DreamTime would start up normally.

**Screenshots**

**Enviroment (please complete the following information):**
 - DreamTime Version 1.5.5
 - OS: Windows 10
 - RAM: 6 GB
 - GPU: 

**Additional context**

Error: [752] Failed to execute script main
Traceback (most recent call last):
  File "main.py", line 9, in <module>
  File "C:\hostedtoolcache\windows\Python\3.7.8\x64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "argv\__init__.py", line 9, in <module>
  File "C:\hostedtoolcache\windows\Python\3.7.8\x64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "argv\daemon.py", line 3, in <module>
  File "C:\hostedtoolcache\windows\Python\3.7.8\x64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "daemon.py", line 11, in <module>
  File "C:\hostedtoolcache\windows\Python\3.7.8\x64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module

**Comment by kolessios** [comment]
Check if you have this file: `C:\Windows\System32\libiomp5md.dll` if so, delete or rename it and try again.
