### ISSUE TITLE
Impossible to install with the Windows Installer

### ISSUE THREAD

**Issue by thistehneisen** [dreamnettech/dreamtime#184]
**Describe the bug**
Error: The system cannot find the file specified.
    at Object.fromBuffer (C:\Users\putni\AppData\Local\Programs\DreamTime\resources\app.asar\node_modules\node-7z\src\error.js:30:15)
    at C:\Users\putni\AppData\Local\Programs\DreamTime\resources\app.asar\node_modules\node-7z\src\events.js:25:19
    at Socket.<anonymous> (C:\Users\putni\AppData\Local\Programs\DreamTime\resources\app.asar\node_modules\node-7z\src\lifecycle.js:64:51)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:268:9)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
OK

Error: The system cannot find the file specified.
    at Object.fromBuffer (C:\Users\putni\AppData\Local\Programs\DreamTime\resources\app.asar\node_modules\node-7z\src\error.js:30:15)
    at C:\Users\putni\AppData\Local\Programs\DreamTime\resources\app.asar\node_modules\node-7z\src\events.js:25:19
    at Socket.<anonymous> (C:\Users\putni\AppData\Local\Programs\DreamTime\resources\app.asar\node_modules\node-7z\src\lifecycle.js:64:51)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:268:9)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
OK

**To Reproduce**
Probably just try on Windows 10. Did try with administrator permissions, changing the folders where file is downloaded etc. and no luck.

**Expected behavior**
To install.

**Screenshots**

**Enviroment (please complete the following information):**
 - DreamTime Version 1.5.9
 - OS: Windows 10 1803
 - RAM: 16 GB
 - GPU: RTX 2070 8 GB VRAM

**Additional context**
Also, I have a feeling that it deletes all of the folders contents. In my case, I chose Downloads Folder luckily, but if someone adds in Documents, it could be painful. Would suggest to recheck.

**Comment by thistehneisen** [comment]
Portable version gets the "DreamPower-v1.2.13-windows-any.7z" file successfully, but afterwards goes into endless loading loop.
