### ISSUE TITLE
ERROR INSTALLING DreamTime and DreamPower

### ISSUE THREAD

**Issue by RuyMatheusDal** [dreamnettech/dreamtime#290]
I installed everything manually, I've done it several times to make sure I didn't make a mistake. But it always gives this error when I run "dreamtimetech"

I'm using very good Machine Learning on Azure.

root@deepn:/run/user# dreamtimetech
WebTorrent: uTP not supported
12:15:34 AM [INFO]  06827f;1melectron: Booting...
12:15:34 AM [DEBUG] 06827f;1melectron: Enviroment: production
12:15:34 AM [DEBUG] 06827f;1melectron: Portable: No
12:15:34 AM [DEBUG] 06827f;1melectron: App Path: /snap/dreamtimetech/22/resources/app.asar
12:15:34 AM [DEBUG] 06827f;1melectron: Exe Path: /snap/dreamtimetech/22/dreamtimetech
12:15:34 AM [DEBUG] 06827f;1melectron: ENV Path: /snap/dreamtimetech/22/.env
Error: /root/snap/dreamtimetech/22/.config/dreamtime/settings.json: ENOENT: no such file or directory, open '/root/snap/dreamtimetech/22/.config/dreamtime/settings.json'
    at Object.openSync (fs.js:476:3)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1846)
    at Object.readFileSync (fs.js:377:35)
    at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8872)
    at Object.readFileSync (/snap/dreamtimetech/22/resources/app.asar/node_modules/jsonfile/index.js:50:22)
    at Proxy.load (/snap/dreamtimetech/22/resources/app.asar/electron/dist/modules/settings.js:9:95)
    at Proxy.boot (/snap/dreamtimetech/22/resources/app.asar/electron/dist/modules/settings.js:20:50)
    at Function.boot (/snap/dreamtimetech/22/resources/app.asar/electron/dist/index.js:13:25)
    at Object.<anonymous> (/snap/dreamtimetech/22/resources/app.asar/electron/dist/index.js:58:246)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Object.<anonymous> (electron/js2c/browser_init.js:193:3237)
    at Object../lib/browser/init.ts (electron/js2c/browser_init.js:193:3441) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/root/snap/dreamtimetech/22/.config/dreamtime/settings.json'
}
The futex facility returned an unexpected error code.Aborted (core dumped)

This is the error that appears.

I manually installed DreamPower, Checkpoints and Waifu2X

I created a folder with their name inside the snap/dreamtimetech folder.

I downloaded the file and extracts it in each folder the way you said and it still gives an error.

![image](https://user-images.githubusercontent.com/99027023/152620256-2ae47c19-fc0e-4ea2-bf9e-2ef8b880363d.png)

These are the 3 folders you need to create, and they are inside this dreamtimetech folder.

Am I right? Or is it wrong?

**Comment by RuyMatheusDal** [comment]
![image](https://user-images.githubusercontent.com/99027023/152620143-40b301da-aa11-4a0f-8292-deab3a500ebc.png)

**Comment by kolessios** [comment]
The error shown is "normal" and only appears during the creation of the configuration file. However the important thing here is that I believe you are trying to run DreamTime (which is a GUI) on a VPS. Maybe you are getting confused and really want to run [DreamPower](https://github.com/dreamnettech/dreampower) which is the command line tool.

Also keep in mind that the development of DreamTime and DreamPower has stopped and support for these projects is minimal.

**Comment by RuyMatheusDal** [comment]
@kolessios So I got very confused. But I've also tried installing DreamPower and it still gives an error.

Can you help me?

Show me a detailed step by step, or really quick just to cosnegui use.
