### ISSUE TITLE
Transformation #1 failed

### ISSUE THREAD

**Issue by 0x6b656e** [dreamnettech/dreamtime#97]
The process has been interrupted by an unknown error, this may be caused by a corrupt installation, please check the console for more information.

For more information please report the following URL on Github or here: https://rollbar.com/occurrence/uuid/?uuid=a886221b-4739-44d2-c289-0400a730a3c1
```
> Traceback (most recent call last):
 File "C:\BuildAgent\work\19c514061bf819a4\src\cli\main.py", line 346, in <module>
 File "C:\BuildAgent\work\19c514061bf819a4\src\cli\main.py", line 243, in main
 File "C:\BuildAgent\work\19c514061bf819a4\src\cli\run.py", line 151, in process
 File "C:\BuildAgent\work\19c514061bf819a4\src\cli\gan.py", line 100, in inference
 File "C:\BuildAgent\work\19c514061bf819a4\src\cli\gan.py", line 259, in forward
 File "C:\Program Files\Python36\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
 File "C:\Program Files\Python36\lib\site-packages\torch\nn\modules\container.py", line 92, in forward
 File "C:\Program Files\Python36\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
 File "C:\Program Files\Python36\lib\site-packages\torch\nn\modules\conv.py", line 338, in forward
 RuntimeError: Expected tensor for argument #1 'input' to have the same device as tensor for argument #2 'weight'; but device 0 does not equal 1 (while checking arguments for cudnn_convolution)
> [24056] Failed to execute script main
> Executing phase: correct_to_mask
> Executing phase: dress_to_correct
> GPU IDs: [1]
```

**Comment by kolessios** [comment]
Thank you for your report, this is the first time I see this error message so I have two questions for you:

1. Do you have multiple GPUs?
2. In "Settings" which option you have selected in "Device" and/or "GPU".

**Comment by 0x6b656e** [comment]
Yes I do and the correct GPU is #1. The one listed as GPU 0 is not a
capable gpu. The card known as #1 is a 1080ti with latest drivers as of
right before this error
